# staging-deployment.yml
location: australiaeast
name: ${{ env.DEPLOYMENT_NAME }}  # Name for the container group
type: Microsoft.ContainerInstance/containerGroups
properties:
  containers:
    - name: product-service
      properties:
        image: 224917579.azurecr.io/product_service:latest
        ports:
          - port: 8001
        environmentVariables:
          - name: PRODUCT_API_BASE_URL
            value: http://localhost:8001
        resources:
          requests:
            cpu: 1.0
            memoryInGb: 1.5
    - name: order-service
      properties:
        image: 224917579.azurecr.io/order_service:latest
        ports:
          - port: 8002
        environmentVariables:
          - name: ORDER_API_BASE_URL
            value: http://localhost:8002
        resources:
          requests:
            cpu: 1.0
            memoryInGb: 1.5
    - name: customer-service
      properties:
        image: 224917579.azurecr.io/customer_service:latest
        ports:
          - port: 8003
        environmentVariables:
          - name: CUSTOMER_API_BASE_URL
            value: http://localhost:8003
        resources:
          requests:
            cpu: 1.0
            memoryInGb: 1.5
    - name: frontend
      properties:
        image: 224917579.azurecr.io/frontend:latest
        ports:
          - port: 80
        environmentVariables:
          - name: PRODUCT_API_BASE_URL
            value: http://product-service:8001
          - name: ORDER_API_BASE_URL
            value: http://order-service:8002
          - name: CUSTOMER_API_BASE_URL
            value: http://customer-service:8003
        resources:
          requests:
            cpu: 1.0
            memoryInGb: 1.5
  osType: Linux
  ipAddress:
    type: Public
    ports:
      - protocol: tcp
        port: 8001
      - protocol: tcp
        port: 8002
      - protocol: tcp
        port: 8003
      - protocol: tcp
        port: 80
  restartPolicy: Always
  imageRegistryCredentials:
    - server: 224917579.azurecr.io
      username: ${{ secrets.AZURE_ACR_USERNAME }}
      password: ${{ secrets.AZURE_ACR_PASSWORD }}
