name: CD Pipeline - Staging and Cleanup

on:
  push:
    branches:
      - 'testing'
  # workflow_call:
  # workflow_run:
  #   workflows: ["CI Pipeline - Test, Build and Push Images to ACR"]
  #   types:
  #     - completed
  

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_STAGING_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  STAGING_LOCATION: 'australiaeast'
  DEPLOYMENT_NAME: 'staging-deployment'
  PRODUCT_PORT: 8000
  ORDER_PORT: 8001
  CUSTOMER_PORT: 8002
  FRONTEND_PORT: 80

jobs:
  deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Azure Login for ACR
        run: |
          az acr login --name ${{ env.AZURE_CONTAINER_REGISTRY }}

      # - name: Deploy to Azure Container Instances
      #   id: deploy
      #   run: |
      #     az container create \
      #       --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
      #       --name ${{ env.DEPLOYMENT_NAME }} \
      #       --file ./docker-compose.yml \
      #       --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }} \
      #       --ip-address Public \
      #       --ports ${{ env.FRONTEND_PORT }}

      - name: Deploy product_service to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
            --name product-service-instance \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}/product_service:latest \
            --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }} \
            --ip-address Public \
            --ports ${{ env.PRODUCT_PORT }}

      - name: Get product_service IP
        run: |
          ip=$(az container show \
            --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
            --name product-service-instance \
            --query ipAddress.ip \
            --output tsv)
          echo "PRODUCT_API_IP=$ip" >> $GITHUB_ENV

      - name: Deploy order_service to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
            --name order-service-instance \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}/order_service:latest \
            --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }} \
            --ip-address Public \
            --ports ${{ env.ORDER_PORT }}

      - name: Get order_service IP
        run: |
          ip=$(az container show \
            --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
            --name order-service-instance \
            --query ipAddress.ip \
            --output tsv)
          echo "ORDER_API_IP=$ip" >> $GITHUB_ENV

      - name: Deploy customer_service to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
            --name customer-service-instance \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}/customer_service:latest \
            --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }} \
            --ip-address Public \
            --ports ${{ env.CUSTOMER_PORT }}

      - name: Get customer_service IP
        run: |
          ip=$(az container show \
            --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
            --name customer-service-instance \
            --query ipAddress.ip \
            --output tsv)
          echo "CUSTOMER_API_IP=$ip" >> $GITHUB_ENV

      - name: Inject Backend IPs into Frontend main.js
        run: |
          echo "Injecting IPs into frontend/static/js/main.js"

          sed -i "s|PRODUCT_API_BASE_URL|http://${{ env.PRODUCT_API_IP }}|g" frontend/static/js/main.js
          sed -i "s|ORDER_API_BASE_URL|http://${{ env.ORDER_API_IP }}|g" frontend/static/js/main.js
          sed -i "s|CUSTOMER_API_BASE_URL|http://${{ env.CUSTOMER_API_IP }}|g" frontend/static/js/main.js

          echo "--- Modified main.js content ---"
          cat frontend/static/js/main.js
          echo "---------------------------------"

      - name: Build and push customer_service image
        run: |
          docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}/frontend:latest ./frontend
          docker push ${{ env.AZURE_CONTAINER_REGISTRY }}/frontend:latest

      - name: Deploy frontend to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
            --name frontend-instance \
            --image ${{ env.AZURE_CONTAINER_REGISTRY }}/frontend:latest \
            --registry-login-server ${{ env.AZURE_CONTAINER_REGISTRY }} \
            --ip-address Public \
            --ports ${{ env.FRONTEND_PORT }}

      - name: Get frontend IP
        run: |
          ip=$(az container show \
            --resource-group ${{ env.AZURE_STAGING_RESOURCE_GROUP }} \
            --name frontend-instance \
            --query ipAddress.ip \
            --output tsv)
          echo "FRONTEND_API_IP=$ip" >> $GITHUB_ENV

      - name: Wait for manual acceptance testing (e.g., 5 minutes)
        run: |
          echo "Staging environment is ready at http://${{ env.STAGING_IP_ADDRESS }}. You have 5 minutes to perform manual tests."
          sleep 300 # Wait for 5 minutes

      - name: Destroy staging environment
        if: always()
        run: |
          az group delete --name ${{ env.AZURE_STAGING_RESOURCE_GROUP }} --yes --no-wait
          echo "Staging resource group '${{ env.AZURE_STAGING_RESOURCE_GROUP }}' is being deleted."